// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchqwuyxwdxxizuhdsft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaHF3dXl4d2R4eGl6dWhkc2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTc0NjUsImV4cCI6MjA3MzUzMzQ2NX0.SiXrEAOJ8FXNOQvHwZqbYXBR8WmbPRGv86LPJfLHhpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});